name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to EC2
        run: |
          scp -i luminar_app_final.pem -r ./* 13.234.67.64:~/luminar
          ssh -i luminar_app_final.pem ubuntu@13.234.67.64 'cd ~/luminar && source venv/bin/activate && python manage.py migrate && python manage.py collectstatic && sudo systemctl restart gunicorn'
