# Generated by Django 4.2.3 on 2023-07-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=255)),
                ('class_attended', models.IntegerField(default=0)),
                ('total_classes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('offline', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='DemoClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.CharField(default='6 months', max_length=300)),
                ('offline_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('online_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
            ],
        ),
        migrations.CreateModel(
            name='JobPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_title', models.CharField(max_length=300)),
                ('location', models.CharField(default='eranakulam', max_length=200)),
                ('salary', models.PositiveIntegerField()),
                ('bond', models.PositiveIntegerField()),
                ('url_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=300)),
                ('trainer_name', models.CharField(max_length=300)),
                ('time', models.TimeField()),
                ('status', models.BooleanField(default=True)),
                ('url_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
                ('description', models.TextField(default=False)),
                ('full_name', models.CharField(default=False, max_length=100)),
                ('cochin', models.CharField(default=False, max_length=100)),
                ('calicut', models.CharField(default=False, max_length=100)),
                ('duration', models.CharField(default='6 months', max_length=300)),
                ('offline_fees', models.DecimalField(decimal_places=2, default=False, max_digits=10)),
                ('online_fees', models.DecimalField(decimal_places=2, default=False, max_digits=10)),
                ('mod_no1', models.CharField(default='', max_length=100)),
                ('mod1_heading', models.TextField(default=False)),
                ('mod1_text', models.TextField()),
                ('mod_no2', models.CharField(default='', max_length=100)),
                ('mod2_heading', models.TextField(default=False)),
                ('mod2_text', models.TextField()),
                ('mod_no3', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('mod3_heading', models.TextField(blank=True, null=True)),
                ('mod3_text', models.TextField(blank=True, null=True)),
                ('mod_no4', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('mod4_heading', models.TextField(blank=True, null=True)),
                ('mod4_text', models.TextField(blank=True, null=True)),
                ('mod_no5', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('mod5_heading', models.TextField(blank=True, null=True)),
                ('mod5_text', models.TextField(blank=True, null=True)),
                ('mod_no6', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('mod6_heading', models.TextField(blank=True, null=True)),
                ('mod6_text', models.TextField(blank=True, null=True)),
                ('mod_no7', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('mod7_heading', models.TextField(blank=True, null=True)),
                ('mod7_text', models.TextField(blank=True, null=True)),
                ('mod_no8', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('mod8_heading', models.TextField(blank=True, null=True)),
                ('mod8_text', models.TextField(blank=True, null=True)),
                ('mod_no9', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('mod9_heading', models.TextField(blank=True, null=True)),
                ('mod9_text', models.TextField(blank=True, null=True)),
                ('mod_no10', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('mod10_heading', models.TextField(blank=True, null=True)),
                ('mod10_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('batch_code', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=255)),
                ('subjects', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=300)),
                ('test_title', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('total_mark', models.PositiveIntegerField(default=100)),
                ('obtained_mark', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VideoScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('link', models.URLField(default='', null=True)),
                ('thumbnail', models.ImageField(default='', upload_to='thumbnails')),
            ],
        ),
    ]
