# Generated by Django 4.2.3 on 2023-08-03 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='overview',
            name='start_date',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='VideoScreenClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('video_link', models.URLField()),
                ('uploaded_date', models.CharField(max_length=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='luminarapi.democlass')),
            ],
        ),
    ]
