# Generated by Django 4.2.3 on 2023-08-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0002_alter_assignment_date_alter_overview_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='monthly_attedance',
            field=models.IntegerField(default=0),
        ),
    ]
