# Generated by Django 4.2.3 on 2023-07-26 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0002_modules_mod_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='democlass',
            name='description',
        ),
        migrations.RemoveField(
            model_name='democlass',
            name='url_link',
        ),
    ]
