# Generated by Django 4.2.3 on 2023-08-05 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0003_logo_attendance_monthly_attedance'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luminarapi.logo'),
        ),
    ]
