# Generated by Django 4.2.3 on 2023-07-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0003_remove_democlass_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modules',
            old_name='mod_no',
            new_name='mod_no1',
        ),
        migrations.AddField(
            model_name='modules',
            name='mod_no10',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='modules',
            name='mod_no2',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='modules',
            name='mod_no3',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='modules',
            name='mod_no4',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='modules',
            name='mod_no5',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='modules',
            name='mod_no6',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='modules',
            name='mod_no7',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='modules',
            name='mod_no8',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='modules',
            name='mod_no9',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
