# Generated by Django 4.2.3 on 2023-08-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0004_liveclass_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modules',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
