# Generated by Django 4.2.3 on 2023-07-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0004_rename_mod_no_modules_mod_no1_modules_mod_no10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='calicut',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='modules',
            name='cohin',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='modules',
            name='description',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='modules',
            name='duration',
            field=models.CharField(default='6 months', max_length=300),
        ),
        migrations.AddField(
            model_name='modules',
            name='heading1',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='modules',
            name='offline_fees',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='modules',
            name='online_fees',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10),
        ),
    ]
