# Generated by Django 4.2.3 on 2023-07-27 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0005_modules_calicut_modules_cohin_modules_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='heading1',
        ),
    ]
