# Generated by Django 4.2.3 on 2023-07-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0006_remove_modules_heading1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='mod_no10',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='mod_no3',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='mod_no4',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='mod_no5',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='mod_no6',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='mod_no7',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='mod_no8',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='mod_no9',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
    ]
