# Generated by Django 4.2.3 on 2023-07-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0007_alter_modules_mod_no10_alter_modules_mod_no3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='full_name',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
