# Generated by Django 4.1.10 on 2023-07-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0007_remove_modules_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='mod3_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='mod4_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
