# Generated by Django 4.2.3 on 2023-07-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0008_modules_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='mod_no1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='modules',
            name='mod_no10',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='mod_no2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='modules',
            name='mod_no3',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='mod_no4',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='mod_no5',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='mod_no6',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='mod_no7',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='mod_no8',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='mod_no9',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
