# Generated by Django 4.1.10 on 2023-07-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0008_alter_modules_mod3_text_alter_modules_mod4_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='total_classes',
            field=models.IntegerField(default=0),
        ),
    ]
