# Generated by Django 4.1.10 on 2023-07-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0009_alter_attendance_total_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='total_classes',
            field=models.IntegerField(),
        ),
    ]
