# Generated by Django 4.1.10 on 2023-07-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0011_alter_attendance_total_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoscreen',
            name='link',
            field=models.URLField(default='', null=True),
        ),
    ]
