# Generated by Django 4.1.10 on 2023-07-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0012_videoscreen_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoscreen',
            name='thumnail',
            field=models.ImageField(default='', upload_to='thumbnails'),
        ),
    ]
