# Generated by Django 4.1.10 on 2023-07-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0013_videoscreen_thumnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoscreen',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
