name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test

  deploy:
    name: Deploy to Server
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Only deploy on pushes to main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your deployment steps here (e.g., Docker build, push, SSH deployment, etc.)
      # Example:
      # - name: Build and push Docker image
      #   run: |
      #     docker build -t my-django-app .
      #     docker tag my-django-app:latest username/my-django-app:latest
      #     docker login -u username -p ${{ secrets.DOCKERHUB_TOKEN }}
      #     docker push username/my-django-app:latest

      # - name: SSH Deployment
      #   uses: easingthemes/ssh-deploy@v2
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     args: '-o StrictHostKeyChecking=no'
      #     local-dir: './path/to/your/django/app'
      #     remote-dir: '/var/www/html'
