name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install Django djangorestframework Pillow twilio

      - name: Add server public key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan 13.234.67.64 >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          scp -r ./* ubuntu@13.234.67.64:~/luminar
          ssh ubuntu@13.234.67.64 'cd ~/luminar && source venv/bin/activate && python manage.py migrate && python manage.py collectstatic && sudo systemctl restart gunicorn'
